### ISSUE TITLE
Pull requests?

### ISSUE THREAD

**Issue by Jameskmonger** [forty9er/21s#1]
Hi @forty9er ,

Are you accepting PRs on this project? I'd love to get involved!

James

**Comment by forty9er** [comment]
Hi @Jameskmonger, good question! I hadn't expected this to attract any such attention - I'm just building this to improve my JS/TDD and design skills.
What is the content of your proposed PRs? Improvements or contributing towards building the game?
I am keen to collaborate, and also interested in your motivation.

**Comment by Jameskmonger** [comment]
Hi @forty9er, thanks for your reply! I'm currently learning JS (and TypeScript) with TDD and so I'd love to get involved on a lightweight project like `21s` to help me improve my skills.

I'd be happy to submit PRs with either improvements or content contributions.

**Comment by forty9er** [comment]
OK, why not.
I've been slowly implementing features based on this description: [https://github.com/guardian/pairing-tests/tree/master/21s](https://github.com/guardian/pairing-tests/tree/master/21s).

It's probably not ideal, but I'm using the Jasmine Node package described here: [http://jasmine.github.io/2.3/node.html](http://jasmine.github.io/2.3/node.html). To run tests, run ```jasmine``` from the root directory.

Feel free to contribute however you feel and we can discuss.

**Comment by Jameskmonger** [comment]
Thanks! Will send a PR your way when I can! :smile:
